name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  test_osx:
    name: baseinst_mac
    runs-on: macos-13
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: base_inst
        run: tests/test-basic.sh linux_or_osx_base
        


  test_ubuntu_light:
    name: baseinst_linux
    runs-on: ubuntu-22.04
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: base_inst
        run: tests/test-basic.sh linux_or_osx_base

  fs_matrix: 
    strategy:
      matrix:
        fs: ["fedora:38", "ubuntu:22.04", "debian:latest"]
    runs-on: ubuntu-22.04
    steps:
        - name: nspawn
          run: sudo "apt" "install" "-qy" "systemd-container"
        - name: Get source
          uses: actions/checkout@v3
        - name: base_inst
          run: tests/fs.sh "${{ matrix.fs }}" "tests/test-basic.sh" linux_or_osx_base
        - name: full_inst
          run: tests/fs.sh "${{ matrix.fs }}" "tests/test-basic.sh" with_nix_and_brew


