name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  test_osx:
    name: baseinst_mac
    runs-on: macos-13
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: base_inst
        run: |
          ./gear -h
          ./gear up b a mm
          source "${HOME}/.gears"
          ./gear e gdu
          gdu -v
          ./gear e redis-server,lazygit,htop b:rg a:nodejs:node
          type redis-server
          redis-server --version
          type lazygit
          lazygit --version
          type htop
          htop --version
          type rg
          rg --version
          type npm
          npm --version

  test_linux:
    name: baseinst_linux
    runs-on: ubuntu-22.04
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: base_inst
        run: |
          ./gear -h
          ./gear up b a mm
          source "${HOME}/.gears"
          gdu -v
          ./gear e redis-server,lazygit,htop b:rg a:nodejs:node
          type redis-server
          redis-server --version
          type lazygit
          lazygit --version
          type htop
          htop --version
          type rg
          rg --version
          type npm
          npm --version


  test_linux_full:
    name: full_inst_linux
    runs-on: ubuntu-22.04
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: full_inst
        run: |
          ./gear e nix:firefox brew:gdu
          source "${HOME}/.gears"
          gdu-go -v
          firefox --version
          




            
  #
  # test:
  #   name: baseinst
  #   runs-on: ubuntu-22.04
  #
  #   steps:
  #     - name: GetFilesystems
  #       run: |
  #         #sudo apt update
  #         sudo apt-get -qy install podman systemd-container
  #         podman pull fedora:38
  #         podman pull debian:12
  #
  #     - name: Get source
  #       uses: actions/checkout@v3
  #
  #
  #     - name: test
  #       run: |
  #         tests/test.sh fedora:38
  #         tests/test.sh debian:12
  #
