name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  testmac:
    name: baseinst_mac
    runs-on: macos-13
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: test
        run: |
          export foo=bar
          echo $foo
          ./tests/osx.sh
            
           
  #
  # test:
  #   name: baseinst
  #   runs-on: ubuntu-22.04
  #
  #   steps:
  #     - name: GetFilesystems
  #       run: |
  #         #sudo apt update
  #         sudo apt-get -qy install podman systemd-container
  #         podman pull fedora:38
  #         podman pull debian:12
  #
  #     - name: Get source
  #       uses: actions/checkout@v3
  #
  #
  #     - name: test
  #       run: |
  #         tests/test.sh fedora:38
  #         tests/test.sh debian:12
  #
