name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  test:
    name: baseinst
    runs-on: ubuntu-22.04
    
    steps:
      - name: Setup Podman
        run: |
          systemd-nspawn --version || true
          sudo apt update
          sudo apt-get -qy install podman systemd-nspawn
          podman pull fedora:38
          podman pull debian:12

      - name: Get source
        uses: actions/checkout@v3
        

      - name: test
        run: |
          tests/test.sh fedora:38
          tests/test.sh debian:12

