name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  test_osx:
    name: baseinst_mac
    runs-on: macos-13
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: base_inst
        run: tests/test-01.sh osx
        


  test_linux:
    name: baseinst_linux
    runs-on: ubuntu-22.04
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: base_inst
        run: tests/test-01.sh fatlinux


  test_linux_full:
    name: full_inst_linux
    runs-on: ubuntu-22.04
    steps:
      - name: Get source
        uses: actions/checkout@v3
      - name: full_inst
        run: tests/test-02.sh fatlinux

          




            
  #
  # test:
  #   name: baseinst
  #   runs-on: ubuntu-22.04
  #
  #   steps:
  #     - name: GetFilesystems
  #       run: |
  #         #sudo apt update
  #         sudo apt-get -qy install podman systemd-container
  #         podman pull fedora:38
  #         podman pull debian:12
  #
  #     - name: Get source
  #       uses: actions/checkout@v3
  #
  #
  #     - name: test
  #       run: |
  #         tests/test.sh fedora:38
  #         tests/test.sh debian:12
  #
