name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  test:
    name: fedora
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Podman
        run: |
          #sudo apt update
          sudo apt-get -qy install podman
          podman pull fedora:38
          podman pull debian:12

      - name: Get source
        uses: actions/checkout@v3
        

      - name: test
        run: |
          tests/test.sh fedora:38
          tests/test.sh debian:12

